"""
KAVACH-07 — Strategy Base
Defines the core interface for all strategy modules and the signal schema.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger("kavach.strategy_base")

@dataclass(slots=True)
class Signal:
    """Standardized output from an individual strategy module."""
    symbol: str
    side: str  # "LONG", "SHORT", "NEUTRAL"
    confidence: float  # 0.0 to 100.0
    entry: float
    stop_loss: float
    take_profit: float
    rationale: str
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass(slots=True)
class MetaSignal:
    """Consensus signal generated by the MetaStrategy engine."""
    symbol: str
    side: str
    confidence: float
    entry: float
    stop_loss: float
    take_profit: float
    rationale: str
    strategies_fired: List[str]
    regime: str
    timestamp: float = field(default_factory=time.time)
    position_size_usdt: float = 0.0

class StrategyBase:
    """
    Abstract base class for all KAVACH-07 strategies.
    Subclasses must implement generate_signal().
    """

    def __init__(self, config: Dict[str, Any], symbol: str):
        self.config = config
        self.symbol = symbol
        self.strategy_name = self.__class__.__name__
        
        # FIXED: Bug #1 - Search both config sections for parameters
        key = self._config_key()
        s_cfg = config.get("strategies", {}).get(key)
        p2_cfg = config.get("phase2_strategies", {}).get(key)
        
        self._cfg: Dict[str, Any] = s_cfg or p2_cfg or {}
        
        if not self._cfg:
            logger.warning("Strategy %s: empty config block detected for %s", self.strategy_name, symbol)

    def _config_key(self) -> str:
        """Converts CamelCase class name to snake_case config key."""
        name = self.strategy_name
        res = [name[0].lower()]
        for ch in name[1:]:
            if ch.isupper():
                res.append("_")
                res.append(ch.lower())
            else:
                res.append(ch)
        return "".join(res)

    @property
    def weight(self) -> float:
        """Retrieves strategy weight from config."""
        return float(self._cfg.get("weight", 1.0))

    async def generate_signal(self, data_context: Dict[str, Any]) -> Signal:
        """
        Main entry point for strategy logic.
        Must be implemented by subclasses.
        """
        raise NotImplementedError("Strategy subclasses must implement generate_signal()")

    def _create_signal(
        self, 
        side: str, 
        confidence: float, 
        entry: float, 
        stop_loss: float, 
        take_profit: float, 
        rationale: str,
        extra_metadata: Optional[Dict[str, Any]] = None
    ) -> Signal:
        """Helper to construct a standardized Signal object."""
        meta = {"strategy": self.strategy_name}
        if extra_metadata:
            meta.update(extra_metadata)
            
        return Signal(
            symbol=self.symbol,
            side=side,
            confidence=max(0.0, min(100.0, float(confidence))),
            entry=float(entry),
            stop_loss=float(stop_loss),
            take_profit=float(take_profit),
            rationale=rationale,
            metadata=meta
        )

    def _neutral(self, reason: str = "No signal conditions met") -> Signal:
        """Helper to return a neutral signal."""
        return self._create_signal(
            side="NEUTRAL",
            confidence=0.0,
            entry=0.0,
            stop_loss=0.0,
            take_profit=0.0,
            rationale=reason
        )